name: trellis

services:
  trellis:
    image: ghcr.io/pixeloven/trellis-docker/trellis-nvidia:latest
    environment:
      # - PUID=${PUID:-1000}
      # - PGID=${PGID:-1000}
      - TRELLIS_PORT=${TRELLIS_PORT:-7860}
      - ATTENTION_BACKEND=${ATTENTION_BACKEND:-flash-attn}
    ports:
      - "${TRELLIS_PORT:-7860}:7860"
    volumes:
      - ./data/trellis/models:/app/models
      - ./data/trellis/outputs:/app/outputs
      - ./data/trellis/uploads:/app/uploads
      - ./data/trellis/configs:/app/configs
      - ./data/trellis/tmp:/app/tmp
      - ./data/trellis/cache:/home/trellis/.cache
    stop_signal: SIGKILL
    tty: true
    networks:
      - trellis_network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [compute, utility]

networks:
  trellis_network:
    name: trellis_network
    driver: bridge 